# Generated by Django 4.0.5 on 2022-06-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('va1', models.CharField(max_length=100)),
                ('va2', models.CharField(max_length=100)),
                ('va3', models.CharField(max_length=100)),
                ('oat', models.CharField(max_length=100)),
            ],
        ),
    ]
