# Generated by Django 4.0.5 on 2022-06-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aluno', models.CharField(max_length=100)),
                ('Quantidade_de_faltas', models.CharField(max_length=100)),
                ('Notificações', models.CharField(max_length=100)),
            ],
        ),
    ]
